### ISSUE TITLE
Ability to access last error in TooManyTries

### ISSUE THREAD

**Issue by sweethuman** [franckLdx/ts-retry#14]
Please add to `TooManyTries` a field that contains the last Error thrown by the async function, so one can easily access the last error that was thrown and react accordingly.

**Comment by franckLdx** [comment]
When last try failed on error, this last error is thrown, not TooManyTries. But I will add the last result in TooManyTries

**Comment by franckLdx** [comment]
Done in 4.0.0

**Comment by franckLdx** [comment]
Dine in 4.0.0
