### ISSUE TITLE
esm/cjm modules do not export retryUntilDefined / retryUntilDefinedDecorator

### ISSUE THREAD

**Issue by dmoebius** [franckLdx/ts-retry#25]
`retryUntilDefined` and `retryUntilDefinedDecorator` are missing in the top-level `index.d.ts` in the npm package. Would be fine if they get exported there so that I can use `import {retryUntilDefined} from 'ts-retry'`.

The other util functions such as `retryUntilTruthy` etc. are there.

**Comment by franckLdx** [comment]
Fixed in 4.2.1
